"""empty message

Revision ID: 38843a3677bd
Revises: 
Create Date: 2021-10-20 11:47:02.852546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38843a3677bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sumDb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_number', sa.Float(), nullable=False),
    sa.Column('second_number', sa.Float(), nullable=False),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sumDb')
    # ### end Alembic commands ###
